dates: remove
replacement:
  style: asterisk
eval:
  enabled: false
  gold_dir: ""
filters: config/default_filters.json
whitelist:
  - resources/whitelists/whitelist_plus_fps_091718_nonames.json
blacklist:
  - resources/blacklists/firstnames_minus_fps.json
xml: config/phi_notes_i2b2.json
stanford_ner_tagger: {}
freq_table: false
initials: true
coords: config/coordinates.json
eval_out: philter_ucsf/data/phi
ucsfformat: false
cachepos: ""
verbose: true
